---

- name: "Playbook to test Napalm-Ansible"
  hosts: all
  connection: network_cli

  tasks:
    - name: "Retrieve device facts from via Napalm"
      napalm_get_facts: 
        hostname: "{{ inventory_hostname }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        dev_os: "{{ napalm_platform }}"

      register: result

    - name: "Print results"
      debug:
        msg: "{{ result }}"